2022-01-25 01:07:54,979 Downloading and reading artifact
2022-01-25 01:07:56,573 Splitting data into train and test
Traceback (most recent call last):
  File "/home/pedro.vaz/Documents/mlprojects/udacity_mlops/machine_learning_pipelines/lesson-2-data-exploration-and-preparation/exercises/exercise_6/starter/run.py", line 122, in <module>
    go(args)
  File "/home/pedro.vaz/Documents/mlprojects/udacity_mlops/machine_learning_pipelines/lesson-2-data-exploration-and-preparation/exercises/exercise_6/starter/run.py", line 34, in go
    splits["train"], splits["test"] = train_test_split(df, test_size=args.test_size, random_state=args.random_state,
  File "/home/pedro.vaz/miniconda3/envs/mlflow-b536c99cab3f07bfeb0a1ad9e153575c07cd087e/lib/python3.9/site-packages/sklearn/model_selection/_split.py", line 2197, in train_test_split
    train, test = next(cv.split(X=arrays[0], y=stratify))
  File "/home/pedro.vaz/miniconda3/envs/mlflow-b536c99cab3f07bfeb0a1ad9e153575c07cd087e/lib/python3.9/site-packages/sklearn/model_selection/_split.py", line 1793, in split
    y = check_array(y, ensure_2d=False, dtype=None)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-b536c99cab3f07bfeb0a1ad9e153575c07cd087e/lib/python3.9/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-b536c99cab3f07bfeb0a1ad9e153575c07cd087e/lib/python3.9/site-packages/sklearn/utils/validation.py", line 667, in check_array
    n_samples = _num_samples(array)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-b536c99cab3f07bfeb0a1ad9e153575c07cd087e/lib/python3.9/site-packages/sklearn/utils/validation.py", line 202, in _num_samples
    raise TypeError("Singleton array %r cannot be considered"
TypeError: Singleton array array('genre', dtype='<U5') cannot be considered a valid collection.
