2022-01-30 23:49:33,905 Downloading and reading test artifact
2022-01-30 23:49:35,207 Extracting target from dataframe
2022-01-30 23:49:35,209 Downloading and reading the exported model
wandb: ERROR Project pedrovaz/exercise_12 does not contain artifact: "model_export:latest"
Traceback (most recent call last):
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
ValueError: Project pedrovaz/exercise_12 does not contain artifact: "model_export:latest"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 86, in <module>
    go(args)
  File "run.py", line 31, in go
    model_export_path = run.use_artifact(args.model_export).download()
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 1957, in use_artifact
    artifact = public_api.artifact(type=type, name=name)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/normalize.py", line 62, in wrapper
    six.reraise(CommError, CommError(message, err), sys.exc_info()[2])
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/normalize.py", line 24, in wrapper
    return func(*args, **kwargs)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/public.py", line 520, in artifact
    artifact = Artifact(self.client, entity, project, artifact_name)
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/public.py", line 2583, in __init__
    self._load()
  File "/home/pedro.vaz/miniconda3/envs/mlflow-9ad98997f01f10ca95d41cc160bcad3e8dac16f6/lib/python3.8/site-packages/wandb/apis/public.py", line 3097, in _load
    raise ValueError(
wandb.errors.error.CommError: Project pedrovaz/exercise_12 does not contain artifact: "model_export:latest"
